version: '3.9'

services:
  app:
    container_name: pi-backend
    # restart: always
    build: .
    ports:
      - 4001:4001
    links:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo/reachoutnet
  mongo:
    container_name: pi-mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db